# Laboratory Seven
## Your Name


In [1]:
# Cell 1
# Python program to implement matrix inversion using Gauss-Jordan elimination
# This assignment will not utilize subroutines
import numpy as np

# Steps 1- 4
A=np.array([[3,-7,45,21],[12,11,10,17],[6,25,-80,-24],[17,55,-9,7]])
print(A)

# Step 5


# Step 6


# Step 7 print the inverse




[[  3  -7  45  21]
 [ 12  11  10  17]
 [  6  25 -80 -24]
 [ 17  55  -9   7]]


In [ ]:
# Cell 2
# Invert A by using linalg.inv() function

# Cell 3

_Compare and contrast the results found in cells 1 and 2. Include in your discussion mathematical accuracy and ease of use_

