#### Lecture 22, November 13



In [13]:
import numpy as np
from scipy import linalg

A=np.array([[4.0,7.0],[2.0,6.0]])
#
# print array
print("Matrix A")
print(A)
#
# print dimensions of A
print("dimension of A")
print(np.shape(A))
#
# print transpose of A
print("Transpose of A")
B=A.T
print(B)
#
# find A inverse
A_inv=linalg.inv(A)
print("A inverse")
print(A_inv)
#
# multiply A-inverse * A
C=A @ A_inv
print("A times A-inverse")
print(C)

Matrix A
[[4. 7.]
 [2. 6.]]
dimension of A
(2, 2)
Transpose of A
[[4. 2.]
 [7. 6.]]
A inverse
[[ 0.6 -0.7]
 [-0.2  0.4]]
A-inverse times A
[[1. 0.]
 [0. 1.]]
